### ISSUE TITLE
Is this an active project?

### ISSUE THREAD

**Issue by signalnerve** [tcurdt/iProxy#30]
@tcurdt – is this still considered an active project? 

AFAIK, there isn't many other options like this out there that function as well as this did. That being said, the chances of it being runnable upon immediate download is becoming more and more unlikely, from iOS 5, to iOS 6, to iOS 7, etc. 

There's a couple PRs that seem to keep it up-to-date. I'm not a great iOS developer, but I'd love to fork the project and accept some pull requests so that it can continue to be usable on newer operating systems. 

Interested to hear some other opinions from other people who have recently (though that's subjective, considering the last update was 1+ years ago) contributed to the project – @atomicbird, @racnot, etc. 

If there is another alternative that someone knows of, it might not be a bad idea to document that in the README, as this is a fairly popular project in terms of stars/forks.

**Comment by jquick** [comment]
I know this is a dead project. But now that xcode 7 is coming out and anyone can sideload apps this is going to be a huge win for iphone users. I looked around at the forks but did not see anything recent. The iphone-socks-proxy also looks dead. If anyone knows of something recent please let me know. If not I may try to upgrade one of these.

**Comment by tcurdt** [comment]
Well, if anyone wants to bring things up to speed I am more than happy merge a pull request or even pass on commit access.

**Comment by arthurcolle** [comment]
Hey anyone been messing around with this recently? Figured it was worth a shot to ask!

**Comment by crstdav** [comment]
its working actually with latest ios ? ios 10/11 , xcode 8/9 ?

**Comment by tcurdt** [comment]
I would check the forks. Not much has happened here the past few years. I don't have the need or time for active development - but I am always happy to merge up-to-date forks.

**Comment by harhoang** [comment]
Ah that explains why none of this is working in ios10
