### ISSUE TITLE
iProxy crashes on launch on Xcode 13.1 for iOS 15

### ISSUE THREAD

**Issue by mozeryansky** [tcurdt/iProxy#34]
The project is working fine but I needed to do just a couple things to get it to work on the latest xcode/iOS versions, so I wanted to file a ticket for the next person.

I allowed Xcode to auto update the project, but I needed to delete the manual provisioning profiles.

In `AppDelete.m` change `[window addSubview:statusViewController.view];` to `[window setRootViewController:statusViewController];` as it would crash complaining about no root view controller.

Everything else was fine and I was able to proxy from my mac to my phone.

**Comment by tcurdt** [comment]
I am surprised this is all that is needed. Want to create a PR?

**Comment by mozeryansky** [comment]
@tcurdt There were a few other xcode project related changes, but the only code change was `setRootViewController`. I submitted a PR with all the changes needed to compile right from a clone. Thanks for the work!

**Comment by JADJO** [comment]
transation direct to my bank account
